# Generated by Django 4.2.16 on 2026-04-29 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game_platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.gameplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_items',
                'indexes': [models.Index(fields=['user', 'game_platform'], name='inventory_i_user_id_23eda6_idx')],
                'unique_together': {('user', 'game_platform')},
            },
        ),
    ]
