# Generated by Django 4.2.16 on 2026-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_game_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
